/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.lisak.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class LunarLanding extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1612265099193707545L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LunarLanding\",\"namespace\":\"org.lisak.avro\",\"fields\":[{\"name\":\"date\",\"type\":\"string\"},{\"name\":\"probeName\",\"type\":\"string\"},{\"name\":\"country\",\"type\":\"string\"},{\"name\":\"missionDetails\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"MissionDetails\",\"fields\":[{\"name\":\"mass\",\"type\":\"int\"},{\"name\":\"launchVehicle\",\"type\":\"string\"},{\"name\":\"goal\",\"type\":\"string\"}]}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LunarLanding> ENCODER =
      new BinaryMessageEncoder<LunarLanding>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LunarLanding> DECODER =
      new BinaryMessageDecoder<LunarLanding>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<LunarLanding> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<LunarLanding> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<LunarLanding> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<LunarLanding>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this LunarLanding to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a LunarLanding from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a LunarLanding instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static LunarLanding fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence date;
  @Deprecated public java.lang.CharSequence probeName;
  @Deprecated public java.lang.CharSequence country;
  @Deprecated public org.lisak.avro.MissionDetails missionDetails;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LunarLanding() {}

  /**
   * All-args constructor.
   * @param date The new value for date
   * @param probeName The new value for probeName
   * @param country The new value for country
   * @param missionDetails The new value for missionDetails
   */
  public LunarLanding(java.lang.CharSequence date, java.lang.CharSequence probeName, java.lang.CharSequence country, org.lisak.avro.MissionDetails missionDetails) {
    this.date = date;
    this.probeName = probeName;
    this.country = country;
    this.missionDetails = missionDetails;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return date;
    case 1: return probeName;
    case 2: return country;
    case 3: return missionDetails;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: date = (java.lang.CharSequence)value$; break;
    case 1: probeName = (java.lang.CharSequence)value$; break;
    case 2: country = (java.lang.CharSequence)value$; break;
    case 3: missionDetails = (org.lisak.avro.MissionDetails)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'date' field.
   * @return The value of the 'date' field.
   */
  public java.lang.CharSequence getDate() {
    return date;
  }


  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(java.lang.CharSequence value) {
    this.date = value;
  }

  /**
   * Gets the value of the 'probeName' field.
   * @return The value of the 'probeName' field.
   */
  public java.lang.CharSequence getProbeName() {
    return probeName;
  }


  /**
   * Sets the value of the 'probeName' field.
   * @param value the value to set.
   */
  public void setProbeName(java.lang.CharSequence value) {
    this.probeName = value;
  }

  /**
   * Gets the value of the 'country' field.
   * @return The value of the 'country' field.
   */
  public java.lang.CharSequence getCountry() {
    return country;
  }


  /**
   * Sets the value of the 'country' field.
   * @param value the value to set.
   */
  public void setCountry(java.lang.CharSequence value) {
    this.country = value;
  }

  /**
   * Gets the value of the 'missionDetails' field.
   * @return The value of the 'missionDetails' field.
   */
  public org.lisak.avro.MissionDetails getMissionDetails() {
    return missionDetails;
  }


  /**
   * Sets the value of the 'missionDetails' field.
   * @param value the value to set.
   */
  public void setMissionDetails(org.lisak.avro.MissionDetails value) {
    this.missionDetails = value;
  }

  /**
   * Creates a new LunarLanding RecordBuilder.
   * @return A new LunarLanding RecordBuilder
   */
  public static org.lisak.avro.LunarLanding.Builder newBuilder() {
    return new org.lisak.avro.LunarLanding.Builder();
  }

  /**
   * Creates a new LunarLanding RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LunarLanding RecordBuilder
   */
  public static org.lisak.avro.LunarLanding.Builder newBuilder(org.lisak.avro.LunarLanding.Builder other) {
    if (other == null) {
      return new org.lisak.avro.LunarLanding.Builder();
    } else {
      return new org.lisak.avro.LunarLanding.Builder(other);
    }
  }

  /**
   * Creates a new LunarLanding RecordBuilder by copying an existing LunarLanding instance.
   * @param other The existing instance to copy.
   * @return A new LunarLanding RecordBuilder
   */
  public static org.lisak.avro.LunarLanding.Builder newBuilder(org.lisak.avro.LunarLanding other) {
    if (other == null) {
      return new org.lisak.avro.LunarLanding.Builder();
    } else {
      return new org.lisak.avro.LunarLanding.Builder(other);
    }
  }

  /**
   * RecordBuilder for LunarLanding instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LunarLanding>
    implements org.apache.avro.data.RecordBuilder<LunarLanding> {

    private java.lang.CharSequence date;
    private java.lang.CharSequence probeName;
    private java.lang.CharSequence country;
    private org.lisak.avro.MissionDetails missionDetails;
    private org.lisak.avro.MissionDetails.Builder missionDetailsBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.lisak.avro.LunarLanding.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.date)) {
        this.date = data().deepCopy(fields()[0].schema(), other.date);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.probeName)) {
        this.probeName = data().deepCopy(fields()[1].schema(), other.probeName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.country)) {
        this.country = data().deepCopy(fields()[2].schema(), other.country);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.missionDetails)) {
        this.missionDetails = data().deepCopy(fields()[3].schema(), other.missionDetails);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (other.hasMissionDetailsBuilder()) {
        this.missionDetailsBuilder = org.lisak.avro.MissionDetails.newBuilder(other.getMissionDetailsBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing LunarLanding instance
     * @param other The existing instance to copy.
     */
    private Builder(org.lisak.avro.LunarLanding other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.date)) {
        this.date = data().deepCopy(fields()[0].schema(), other.date);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.probeName)) {
        this.probeName = data().deepCopy(fields()[1].schema(), other.probeName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.country)) {
        this.country = data().deepCopy(fields()[2].schema(), other.country);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.missionDetails)) {
        this.missionDetails = data().deepCopy(fields()[3].schema(), other.missionDetails);
        fieldSetFlags()[3] = true;
      }
      this.missionDetailsBuilder = null;
    }

    /**
      * Gets the value of the 'date' field.
      * @return The value.
      */
    public java.lang.CharSequence getDate() {
      return date;
    }


    /**
      * Sets the value of the 'date' field.
      * @param value The value of 'date'.
      * @return This builder.
      */
    public org.lisak.avro.LunarLanding.Builder setDate(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.date = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'date' field.
      * @return This builder.
      */
    public org.lisak.avro.LunarLanding.Builder clearDate() {
      date = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'probeName' field.
      * @return The value.
      */
    public java.lang.CharSequence getProbeName() {
      return probeName;
    }


    /**
      * Sets the value of the 'probeName' field.
      * @param value The value of 'probeName'.
      * @return This builder.
      */
    public org.lisak.avro.LunarLanding.Builder setProbeName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.probeName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'probeName' field has been set.
      * @return True if the 'probeName' field has been set, false otherwise.
      */
    public boolean hasProbeName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'probeName' field.
      * @return This builder.
      */
    public org.lisak.avro.LunarLanding.Builder clearProbeName() {
      probeName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'country' field.
      * @return The value.
      */
    public java.lang.CharSequence getCountry() {
      return country;
    }


    /**
      * Sets the value of the 'country' field.
      * @param value The value of 'country'.
      * @return This builder.
      */
    public org.lisak.avro.LunarLanding.Builder setCountry(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.country = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'country' field has been set.
      * @return True if the 'country' field has been set, false otherwise.
      */
    public boolean hasCountry() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'country' field.
      * @return This builder.
      */
    public org.lisak.avro.LunarLanding.Builder clearCountry() {
      country = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'missionDetails' field.
      * @return The value.
      */
    public org.lisak.avro.MissionDetails getMissionDetails() {
      return missionDetails;
    }


    /**
      * Sets the value of the 'missionDetails' field.
      * @param value The value of 'missionDetails'.
      * @return This builder.
      */
    public org.lisak.avro.LunarLanding.Builder setMissionDetails(org.lisak.avro.MissionDetails value) {
      validate(fields()[3], value);
      this.missionDetailsBuilder = null;
      this.missionDetails = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'missionDetails' field has been set.
      * @return True if the 'missionDetails' field has been set, false otherwise.
      */
    public boolean hasMissionDetails() {
      return fieldSetFlags()[3];
    }

    /**
     * Gets the Builder instance for the 'missionDetails' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public org.lisak.avro.MissionDetails.Builder getMissionDetailsBuilder() {
      if (missionDetailsBuilder == null) {
        if (hasMissionDetails()) {
          setMissionDetailsBuilder(org.lisak.avro.MissionDetails.newBuilder(missionDetails));
        } else {
          setMissionDetailsBuilder(org.lisak.avro.MissionDetails.newBuilder());
        }
      }
      return missionDetailsBuilder;
    }

    /**
     * Sets the Builder instance for the 'missionDetails' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public org.lisak.avro.LunarLanding.Builder setMissionDetailsBuilder(org.lisak.avro.MissionDetails.Builder value) {
      clearMissionDetails();
      missionDetailsBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'missionDetails' field has an active Builder instance
     * @return True if the 'missionDetails' field has an active Builder instance
     */
    public boolean hasMissionDetailsBuilder() {
      return missionDetailsBuilder != null;
    }

    /**
      * Clears the value of the 'missionDetails' field.
      * @return This builder.
      */
    public org.lisak.avro.LunarLanding.Builder clearMissionDetails() {
      missionDetails = null;
      missionDetailsBuilder = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LunarLanding build() {
      try {
        LunarLanding record = new LunarLanding();
        record.date = fieldSetFlags()[0] ? this.date : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.probeName = fieldSetFlags()[1] ? this.probeName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.country = fieldSetFlags()[2] ? this.country : (java.lang.CharSequence) defaultValue(fields()[2]);
        if (missionDetailsBuilder != null) {
          try {
            record.missionDetails = this.missionDetailsBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("missionDetails"));
            throw e;
          }
        } else {
          record.missionDetails = fieldSetFlags()[3] ? this.missionDetails : (org.lisak.avro.MissionDetails) defaultValue(fields()[3]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LunarLanding>
    WRITER$ = (org.apache.avro.io.DatumWriter<LunarLanding>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LunarLanding>
    READER$ = (org.apache.avro.io.DatumReader<LunarLanding>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.date);

    out.writeString(this.probeName);

    out.writeString(this.country);

    if (this.missionDetails == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.missionDetails.customEncode(out);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.date = in.readString(this.date instanceof Utf8 ? (Utf8)this.date : null);

      this.probeName = in.readString(this.probeName instanceof Utf8 ? (Utf8)this.probeName : null);

      this.country = in.readString(this.country instanceof Utf8 ? (Utf8)this.country : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.missionDetails = null;
      } else {
        if (this.missionDetails == null) {
          this.missionDetails = new org.lisak.avro.MissionDetails();
        }
        this.missionDetails.customDecode(in);
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.date = in.readString(this.date instanceof Utf8 ? (Utf8)this.date : null);
          break;

        case 1:
          this.probeName = in.readString(this.probeName instanceof Utf8 ? (Utf8)this.probeName : null);
          break;

        case 2:
          this.country = in.readString(this.country instanceof Utf8 ? (Utf8)this.country : null);
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.missionDetails = null;
          } else {
            if (this.missionDetails == null) {
              this.missionDetails = new org.lisak.avro.MissionDetails();
            }
            this.missionDetails.customDecode(in);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










